invoice/urls.py
from django.urls import path

from . import views

app_name = 'invoice'
urlpatterns = [
    path('', views.InvoiceListView.as_view(), name='list'),
    path('create/', views.InvoiceCreateView.as_view(), name='create'),
    path('<slug:slug>/view/printable/', views.InvoicePrintableView.as_view(), name='printable'),
    path('<slug:slug>/view/', views.InvoiceDetailView.as_view(), name='detail'),
    path('<slug:slug>/update/', views.InvoiceUpdateView.as_view(), name='update'),

    path('<int:invoice_pk>/add/<int:challan_pk>/', views.InvoiceChallanOperationView.as_view(), {'operation':'add'}, name='add-challan'),
    path('<int:invoice_pk>/remove/<int:challan_pk>/', views.InvoiceChallanOperationView.as_view(), {'operation':'remove'}, name='remove-challan'),
]

kit/urls.py
from django.urls import path, include

from . import views

app_name = 'kit'
urlpatterns = [
    path('api/', include('kit.api.urls')),

    path('', views.KitListView.as_view(), name='list'),
    path('create/', views.KitCreateView.as_view(), name='create'),
    path('<slug:slug>/update/', views.KitUpdateView.as_view(), name='update'),
    path('<slug:slug>/view/', views.KitDetailView.as_view(), name='detail'),
    path('<slug:slug>/delete/', views.KitDeleteView.as_view(), name='delete'),
    path('<int:pk>/uncomplete/', views.KitUncompleteRedirectView.as_view(), name='uncomplete'),
    path('<int:pk>/change_completion_date/', views.KitChangeCompletionDate.as_view(), name='change-completion-date'),
]

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('expert.urls')),
    path('kit/', include('kit.urls')),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('invoice/', include('invoice.urls')),
    path('worker/', include('worker.urls')),
    path('challan/', include('challan.urls')),
    path('salary/', include('salary.urls')),
    # path('expert/', include('expert.urls')),
    path('admin/', admin.site.urls),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

challan/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from datetime import date

from product.models import Product

def challan_image_path(instance, filename):
    return 'Challan/{}/Images/{}'.format(instance.pk, filename)

class ChallanQuerySet(models.QuerySet):
    def products(self):
        return Product.objects.filter(challan__in=self.all())

    @property
    def quantity(self):
        return sum([i.quantity for i in self.all()])

    @property
    def size(self):
        return round(sum([i.size for i in self.all()]), 2)

    @property
    def value(self):
        return round(sum([i.value for i in self.all()]), 2)

class Challan(models.Model):
    """Container for model that represents Delivery Challan"""
    number = models.IntegerField(
        blank=False,
        unique=True,
        verbose_name=_('Challan Number'),
        help_text=_('Unique number of each delivery challan'),
    )
    date_sent = models.DateField(
        null=True,
        blank=False,
        verbose_name=_('Date of Dispatch'),
        help_text=_('Date at which this challan is dispatched')
    )
    jobwork_gatepass_processed = models.ImageField(
        upload_to=challan_image_path,
        null=True,
        blank=True,
        verbose_name=_('Jobwork GatePass (Processed)'),
        help_text=_('The field for storing the gate pass after it is processed')
    )
    invoice = models.ForeignKey(
        'invoice.Invoice',
        null=True,
        default=None,
        blank=True,
        related_name='challans',
        on_delete=models.SET_DEFAULT,
        help_text=_('The Invoice to which this challan belongs to')
    )
    customer = models.ForeignKey(
        'customer.Customer',
        related_name='challans',
        on_delete=models.SET_DEFAULT,
        null=True,
        default=None,
        help_text=_('The customer for against whom challan is drawn'),
    )

    objects = ChallanQuerySet.as_manager()

    class Meta:
        ordering = ('-number',)

    @staticmethod
    def get_all():
        return Challan.objects.all()

    @property
    def quantity(self):
        return self.products.all().completed().quantity

    @property
    def size(self):
        return self.products.all().completed().size

    @property
    def value(self):
        return round(self.size * 3.5, 2)

    @property
    def return_quantity(self):
        return self.products.all().returned().quantity

    @property
    def return_size(self):
        return self.products.all().returned().size

    # def get_total_quantity(self):
    #     return sum([i.quantity for i in self.products.filter(return_remark='')])

    # def get_total_size(self):
    #     # BUG: exclude the returned products from sum DONE
    #     return round(sum([i.size for i in self.products.filter(return_remark='')]),2)

    def get_total_size_by_fabric(self):
        # ret = {}
        ret = {
            'max': self.products.completed(fabric='max').size,
            'tuff': self.products.completed(fabric='tuff').size,
            'fab': self.products.completed(fabric='fab').size,
            'clear': self.products.completed(fabric='clear').size,
        }
        # ret['max'] = round(sum([i.size for i in self.products.filter(return_remark='', fabric='max')]),2)
        # ret['tuff'] = round(sum([i.size for i in self.products.filter(return_remark='', fabric='tuff')]),2)
        # ret['fab'] = round(sum([i.size for i in self.products.filter(return_remark='', fabric='fab')]),2)
        # ret['clear'] = round(sum([i.size for i in self.products.filter(return_remark='', fabric='clear')]),2)
        return ret

    # def get_total_value(self):
    #     return round(self.size * 3.5, 2)

    # def get_return_quantity(self):
    #     return sum([i.quantity for i in self.products.exclude(return_remark='')])

    # def get_return_size(self):
    #     # BUG: exclude the returned products from sum DONE
    #     return str(round(sum([i.size for i in self.products.exclude(return_remark='')]),2))

    def get_absolute_url(self):
        return reverse('challan:detail', kwargs={'slug': self.number})

    def get_excel_url(self):
        return reverse('challan:excel', kwargs={'pk': self.pk})

    def get_printable_url(self):
        return reverse('challan:printable', kwargs={'slug': self.number})

    def get_delete_url(self):
        return reverse('challan:delete', kwargs={'slug': self.number})

    def get_update_url(self):
        return reverse('challan:update', kwargs={'pk': self.pk})
    
    @staticmethod
    def get_list_url():
        return reverse('challan:list')

    def __str__(self):
        return '{} ({})'.format(self.number, self.date_sent)

expert/models/invoice.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from num2words import num2words
from datetime import date

class Invoice(models.Model):
    number = models.IntegerField(
        blank=False,
        unique=True,
        verbose_name=_('Invoice Number'),
        help_text=_('Unique number of each delivery invoice'),
    )
    date_sent = models.DateField(
        null=True,
        blank=False,
        verbose_name=_('Date of Dispatch'),
        help_text=_('Date at which this invoice was created and dispatched')
    )
    # TODO: add a validator for vNo
    motor_vehicle_number = models.CharField(
        blank=False,
        null=False,
        default='',
        max_length=100,
        verbose_name=_('Motor Vehicle No.'),
        help_text=_('Vehicle number from which the invoice is dispatched'),
    )
    destination = models.CharField(
        blank=False,
        null=False,
        default='',
        max_length=100,
        help_text=_('Detination to which this invoice is dispatched'),
    )

    def add_challan(self, challan):
        """ function to add a challan to self invoice and perform various calculations.
        """
        # TODO: check for the condition if new challan added
        # should have the same customer as the already added challans
        challan.invoice = self
        challan.save()
        self.save()

    def remove_challan(self, challan):
        """ function to remove the given challan from invoice 
        return False if challan is not present in this invoice.
        """
        challan.invoice = None
        challan.save()
        self.save()

    def get_total_quantity(self):
        return sum([i.get_total_quantity() for i in self.challans.all()])

    def get_total_size(self):
        return round(sum([i.get_total_size() for i in self.challans.all()]),2)

    def get_total_value(self):
        return round(self.get_total_size() * 3.5,2)

    def get_total_tax(self):
        ret = {}
        ret['cgst'] = round(self.get_total_value() * 0.06, 2)
        ret['sgst'] = ret['cgst']
        ret['total'] = ret['cgst'] + ret['sgst']
        t = ret['total'] + self.get_total_value()
        x = t*100//1%100
        if x<50:
            x = round(x/100, 2)
            x = -x
        else:
            x = 100 - x
            x = round(x/100, 2)
        ret['roundoff'] = x
        ret['total_words'] = '{} rupees and {} paise'.format(num2words(int(ret['total'])), num2words(int(ret['total']*100)%100))
        return ret

    def get_total_amount(self):
        ret = {}
        ret['amount'] = int(self.get_total_tax()['total'] + self.get_total_tax()['roundoff'] + self.get_total_value())
        ret['words'] = num2words(ret['amount'], lang='en_IN')
        return ret

    def get_total_size_by_fabric(self):
        ret = {'max':0, 'tuff':0, 'fab':0, 'clear':0}
        for c in self.challans.all():
            for i in c.get_total_size_by_fabric():
                ret[i] += c.get_total_size_by_fabric()[i]
        for i in ret:
            ret[i] = round(ret[i], 2)
        return ret

    def get_absolute_url(self):
        return reverse('expert:invoice-detail', kwargs={'slug': self.number})

    def __str__(self):
        return self.number

    def __repr__(self):
        return '<Invoice: {}>'.format(self.number)

invoice/forms.py
from django import forms

from .models import Invoice

class InvoiceUpdateForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = '__all__'

    def clean_number(self):
        number = self.cleaned_data['number']
        print(number)
        if number in [i.number for i in Invoice.objects.all()]:
            print('validation error')
        return number

expert/views/invoice.py
from datetime import date
from django.views.generic import ListView, DetailView, RedirectView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView

from ..models import Challan, Invoice
from ..forms import *

class InvoiceCreateView(PermissionRequiredMixin, CreateView):
    model = Invoice
    fields = '__all__'
    template_name_suffix = '_create_form'
    permission_required = ('expert.view_invoice','expert.add_invoice')

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(*args, **kwargs)
        if Invoice.objects.all().exists():
            initial['number'] = Invoice.objects.all().order_by('-number').first().number + 1
        else:
            initial['number'] = 1
        initial['date_sent'] = date.today()
        initial['destination'] = 'Gandhinagar'
        initial['motor_vehicle_number'] = 'GJ-18-AU-3381'
        return initial

    def get_success_url(self):
        return self.object.get_absolute_url()

class InvoiceListView(PermissionRequiredMixin, ListView):
    model = Invoice
    navigation = 'invoice'
    ordering = ['-number']
    permission_required = ('expert.view_invoice')

class InvoiceDetailView(PermissionRequiredMixin, DetailView):
    model = Invoice
    slug_field = 'number'
    permission_required = ('expert.view_invoice','expert.view_challan')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        challan_list = Challan.objects.filter(invoice=None)
        # this further filters the challan list to only the challans
        # that are compatible with challans already present in invoice.
        if self.object.challans.exists():
            challan_list = challan_list.filter(
                customer=self.object.challans.first().customer
            )
        context['challan_list'] = challan_list.order_by('-number')
        return context
    
class InvoiceChallanOperationView(PermissionRequiredMixin, SingleObjectMixin, RedirectView):
    model = Invoice
    pk_url_kwarg = 'invoice_pk'
    permission_required = (
        'expert.view_invoice', 'expert.view_challan',
        'expert.change_invoice', 'expert.change_challan',
    )

    def get_redirect_url(self, *args, **kwargs):
        invoice = self.get_object()
        challan = Challan.objects.get(id=self.kwargs['challan_pk'])
        if self.kwargs['operation'] == 'add':
            invoice.add_challan(challan)
        else:
            invoice.remove_challan(challan)
        return invoice.get_absolute_url()

class InvoicePrintableView(PermissionRequiredMixin, DetailView):
    model = Invoice
    slug_field = 'number'
    template_name_suffix = '_detail_printable'
    permission_required = ('expert.view_invoice','expert.view_challan')

    def get_context_date(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['challan_list'] = self.object.challans.order_by('number')
        return context

class InvoiceUpdateView(PermissionRequiredMixin, UpdateView):
    model = Invoice
    # fields = '__all__'
    form_class = InvoiceUpdateForm
    template_name_suffix = '_update_form'
    slug_field = 'number'
    permission_required = ('expert.view_invoice','expert.change_invoice')

    def form_valid(self, form):
        print(form.instance.number)
        return super().form_valid(form)

    def form_invalid(self, form):
        print('form is invalid')
        return super().form_invalid(form)

invoice/views.py
from datetime import date
from django.views.generic import ListView, DetailView, RedirectView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView

from .models import Invoice
from challan.models import Challan
from .forms import InvoiceUpdateForm

class InvoiceCreateView(PermissionRequiredMixin, CreateView):
    model = Invoice
    fields = '__all__'
    template_name_suffix = '_create_form'
    permission_required = ('invoice.view_invoice','invoice.add_invoice')

    def get_initial(self, *args, **kwargs):
        initial = super().get_initial(*args, **kwargs)
        if Invoice.objects.all().exists():
            initial['number'] = Invoice.objects.all().order_by('-number').first().number + 1
        else:
            initial['number'] = 1
        initial['date_sent'] = date.today()
        initial['destination'] = 'Gandhinagar'
        initial['motor_vehicle_number'] = 'GJ-18-AU-3381'
        return initial

    def get_success_url(self):
        return self.object.get_absolute_url()

class InvoiceListView(PermissionRequiredMixin, ListView):
    model = Invoice
    navigation = 'invoice'
    ordering = ['-number']
    permission_required = ('invoice.view_invoice')

class InvoiceDetailView(PermissionRequiredMixin, DetailView):
    model = Invoice
    slug_field = 'number'
    navigation = 'invoice'
    permission_required = ('invoice.view_invoice','challan.view_challan')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        challan_list = Challan.objects.filter(invoice=None)
        # this further filters the challan list to only the challans
        # that are compatible with challans already present in invoice.
        if self.object.challans.exists():
            challan_list = challan_list.filter(
                customer=self.object.challans.first().customer
            )
        context['challan_list'] = challan_list.order_by('-number')
        return context
    
class InvoiceChallanOperationView(PermissionRequiredMixin, SingleObjectMixin, RedirectView):
    model = Invoice
    pk_url_kwarg = 'invoice_pk'
    permission_required = (
        'invoice.view_invoice', 'challan.view_challan',
        'invoice.change_invoice', 'challan.change_challan',
    )

    def get_redirect_url(self, *args, **kwargs):
        invoice = self.get_object()
        challan = Challan.objects.get(id=self.kwargs['challan_pk'])
        if self.kwargs['operation'] == 'add':
            invoice.add_challan(challan)
        else:
            invoice.remove_challan(challan)
        return invoice.get_absolute_url()

class InvoicePrintableView(PermissionRequiredMixin, DetailView):
    model = Invoice
    slug_field = 'number'
    template_name_suffix = '_detail_printable'
    permission_required = ('invoice.view_invoice','challan.view_challan')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['challan_list'] = self.object.challans.order_by('number')
        return context

class InvoiceUpdateView(PermissionRequiredMixin, UpdateView):
    model = Invoice
    # fields = '__all__'
    form_class = InvoiceUpdateForm
    template_name_suffix = '_update_form'
    slug_field = 'number'
    permission_required = ('invoice.view_invoice','invoice.change_invoice')

invoice/templates/invoice/invoice_create_form.html
{% extends 'expert/base.html' %}
{% load static %}
{% load add_attr %}

{% block custom_js %}
<script>
	$(document).ready(function() {
		$('#btn-save').on('click', function(e) {
			e.preventDefault();
			$('#btn-submit').click();
		});
	});
</script>
{% endblock %}

{% block custom_navbar %}
<li class="nav-item"><a class="nav-link btn btn-success btn-sm mr-1" type="button" href="" id="btn-save"><i class="fa fa-floppy-o"></i> Save</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-secondary btn-sm mr-1" type="button" href="{{ Invoice.get_list_url }}"><i class="fa fa-arrow-left"></i> Back</a></li>
{% endblock %}

{% block main_content %}
<div class="container d-flex justify-content-center col-11 col-md-9 col-lg-8 col-xl-7">
	<div class="col">
		<div class="heading text-center my-4 h3">Create New Invoice</div>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group row">
				<label for="{{ field.id_for_label }}" class="col-4 col-form-label">{{ field.label }}</label>
				<div class="col-8">
					{{ field|add_attr:"form-control" }}
					{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
					{% endif %}
				</div>
			</div>
			{% endfor %}
			<div class="form-group row d-flex justify-content-center">
				<button type="submit" class="btn btn-outline-success w-50 d-none" id="btn-submit">Update</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}

invoice/templates/invoice/invoice_detail.html
{% extends 'expert/base.html' %}
{% load static %}

{% block custom_css %}
<style>
    .scrollable-dropdown-menu {
        height: auto;
        max-height: 250px;
        overflow-x: hidden;
    }
</style>
{% endblock %}

{% block custom_navbar %}
<li class="nav-item"><a class="nav-link btn btn-sm btn-outline-primary mr-1" type="button" href="{{ invoice.get_printable_url }}"><i class="fa fa-eye"></i> View</a></li>
<li class="nav-item"><a class="nav-link btn btn-sm btn-outline-primary mr-1" type="button" href="{{ invoice.get_update_url }}"><i class="fa fa-pencil"></i> Edit</a></li>
{% endblock %}

{% block main_content %}
<div class="container py-4 col-11 col-md-9 col-lg-8 col-xl-6">
    <div class="row">
        <div class="col heading h5">
            <div class="text-center">
                Overview of Invoice {{ invoice.number }}<br>
                <span class="small text-secondary">To: {{ invoice.challans.first.customer.name }}</span><br>
                <span class="text-secondary small">{{ invoice.date_sent }}</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="list-group w-100 mx-3">
            {% for challan in invoice.challans.all %}
            <div class="list-group-item list-group-item-action d-flex justify-content-between">
                <span class="font-weight-bold">{{ challan.number }}</span>
                <span class="text-secondary small">{{ challan.date_sent }}</span>
                <span>
                    <a href="{% url 'invoice:remove-challan' invoice_pk=invoice.pk challan_pk=challan.pk %}" class="btn btn-sm btn-outline-danger"><i class="fa fa-trash fa-lg"></i></a>
                </span>
            </div>
            {% endfor %}
            <div class="dropdown">
                <button class="list-group-item list-group-item-action list-group-item-info text-center dropdown-toggle" type="button" id="dropdown1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Add New Challan
                </button>
                <div class="dropdown-menu list-group-item-action scrollable-dropdown-menu py-0 my-0" aria-labelledby="dropdown1">
                    {% for challan in challan_list %}
                    <a href="{% url 'invoice:add-challan' invoice_pk=invoice.pk challan_pk=challan.pk %}" class="d-flex dropdown-item list-group-item list-group-item-action">
                        <span>{{ challan.number }}</span>
                        <span class="ml-auto">{{ challan.date_sent }}</span>
                        <span class="ml-auto small text-secondary" style="font-size: .75rem;">{{ challan.customer.name }}</span>
                    </a>
                    {% empty %}
                    <a class="dropdown-item list-group-item list-group-item-action text-center">No more Challans to show</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

invoice/templates/invoice/invoice_list.html
{% extends 'expert/base.html' %}
{% load static %}
{% load humanize %}

{% block custom_js %}
<script>
	$(function() {
		var table = $('#table-invoice-list').DataTable({
			'ordering': false,
			'conditionalPaging': true,
			'searching': false,
			"fnDrawCallback": function(settings) {
				$(settings.nTHead).hide();
			},
			dom: '<"float-right"B>ltip',
			buttons: [{
				text: '<i class="fa fa-plus"></i> Add New',
				className: 'btn btn-info btn-sm font-italic',
				action: function(e, dt, node, config) {
					window.location.href = "{{ Invoice.get_create_url }}";
				}
			}],
		});

		$('#table-invoice-list tbody').on('click', 'tr', function() {
			var url = $(this).attr('data-href');
			window.location.href = url;
		})
	});
</script>
{% endblock %}

{% block custom_css %}
<style>
	ul.pagination > .paginate_button {
		padding: 4px 2px!important;
	}
</style>
{% endblock %}

{% block main_content %}
<div class="container py-0 col-11 col-md-9 col-lg-8 col-xl-6">
	<div class="px-3 h2 text-center m-0 py-1">
		List of Invoices
	</div>
	<div class="row mt-2">
		<div class="col font-italic">
			<table class="hover display row-border table-datatable" id="table-invoice-list">
				<thead>
					<tr>
						<th></th>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
                    {% for invoice in invoice_list %}
                    <tr data-href="{{ invoice.get_absolute_url }}">
						<td class="font-weight-bold text-center">{{ invoice.number }}</td>
						<td class="small text-secondary text-center">{{ invoice.challans.first.customer.name|default:"N/A" }}</td>
                        <td class="small text-secondary text-right">{{ invoice.date_sent|naturalday|title }}</td>
                    </tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

invoice/templates/invoice/invoice_update_form.html
{% extends 'expert/base.html' %}
{% load static %}
{% load add_attr %}

{% block custom_js %}
<script>
	$(document).ready(function() {
		$('#btn-update').on('click', function(e) {
			e.preventDefault();
			$('#btn-submit').click();
		});
	});
</script>
{% endblock %}

{% block custom_navbar %}
<li class="nav-item"><a class="nav-link btn btn-success btn-sm mr-1" type="button" href="" id="btn-update"><i class="fa fa-pencil-square-o"></i> Update</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-secondary btn-sm mr-1" type="button" href="{{ invoice.get_absolute_url }}"><i class="fa fa-arrow-left"></i> Back</a></li>
{% endblock %}

{% block main_content %}
<div class="container d-flex justify-content-center col-11 col-md-9 col-lg-8 col-xl-7">
	<div class="col">
		<div class="heading text-center my-4 h3">Update Invoice</div>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group row">
				<label for="{{ field.id_for_label }}" class="col-4 col-form-label">{{ field.label }}</label>
				<div class="col-8">
                    {% if field.errors %}
                    <small class="form-text text-danger font-weight-bold">{{ field.errors }}</small>
                    {{ field|add_attr:"form-control border border-danger" }}
                    {% else %}
					{{ field|add_attr:"form-control" }}
                    {% endif %}
					{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
					{% endif %}
				</div>
			</div>
			{% endfor %}
			<div class="form-group row d-flex justify-content-center">
				<button type="submit" class="btn btn-outline-success w-50 d-none" id="btn-submit">Update</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}