challan/urls.py
from django.urls import path

from . import views

app_name = 'challan'
urlpatterns = [
    path('', views.ChallanListView.as_view(), name='list'),
    path('<slug:slug>/view/', views.ChallanDetailView.as_view(), name='detail'),
    path('<int:pk>/create/', views.ChallanCreateRedirectView.as_view(), name='create'),
    path('<slug:slug>/view/printable/', views.ChallanPrintableView.as_view(), name='printable'),
    path('<slug:slug>/delete/', views.ChallanDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', views.ChallanUpdateView.as_view(), name='update'),
    # url loading the gatepass 
    path('<int:pk>/gatepass/', views.challan_gatepass, name='gatepass'),
    path('<int:pk>/excel/', views.challan_excel, name='excel'),
]

kit/urls.py
from django.urls import path, include

from . import views

app_name = 'kit'
urlpatterns = [
    path('api/', include('kit.api.urls')),

    path('', views.KitListView.as_view(), name='list'),
    path('create/', views.KitCreateView.as_view(), name='create'),
    path('<slug:slug>/update/', views.KitUpdateView.as_view(), name='update'),
    path('<slug:slug>/view/', views.KitDetailView.as_view(), name='detail'),
    path('<slug:slug>/delete/', views.KitDeleteView.as_view(), name='delete'),
    path('<int:pk>/uncomplete/', views.KitUncompleteRedirectView.as_view(), name='uncomplete'),
    path('<int:pk>/change_completion_date/', views.KitChangeCompletionDate.as_view(), name='change-completion-date'),
]

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('expert.urls')),
    path('kit/', include('kit.urls')),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('invoice/', include('invoice.urls')),
    path('worker/', include('worker.urls')),
    path('challan/', include('challan.urls')),
    path('salary/', include('salary.urls')),
    # path('expert/', include('expert.urls')),
    path('admin/', admin.site.urls),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from datetime import date
from dateutil.relativedelta import relativedelta as timedelta

class ProductQuerySet(models.QuerySet):
    def get_date_completed_range(self, start_date, end_date=None):
        if isinstance(start_date, str) or isinstance(end_date, str):
            raise TypeError('start_date and end_date should be of type datetime.date object')
        if end_date is None:
            end_date = start_date + timedelta(months=1) - timedelta(days=1)
        return self.filter(date_completed__lte=end_date, date_completed__gte=start_date)

    def pending(self, **kwargs):
        return self.filter(status='pending').filter(**kwargs)

    def assigned(self, **kwargs):
        return self.filter(status='assigned').filter(**kwargs)

    def completed(self, **kwargs):
        return self.filter(status='completed').filter(**kwargs)

    def returned(self, **kwargs):
        return self.filter(status='returned').filter(**kwargs)

    def dispatched(self, **kwargs):
        return self.filter(dispatched=True).filter(**kwargs)

    def remaining(self, **kwargs):
        return self.filter(dispatched=False).filter(**kwargs)

    @property
    def quantity(self):
        """returns the sum of quantity of the products in filter"""
        if not self.exists():
            return 0
        return sum([i.quantity for i in self.all()])

    @property
    def size(self):
        """returns the sum of the size of the products in filter (rounded 2)"""
        if not self.exists():
            return 0.0
        return round(sum([i.size for i in self.all()]), 2)

    @property
    def value(self):
        if not self.exists():
            return 0
        return round(sum([i.value for i in self.all()]), 2)

class Product(models.Model):
    COLOR_CHOICES = [
        ('black','Black'),
        # account for biege
        ('beige','Beige'),
        ('blue','Blue'),
        ('white','White'),
        ('brown','Brown'),
        ('green','Green'),
        ('sand','Sand'),
        # account for burgandy
        ('burgundy','Burgundy'),
        # account for gray, grey
        ('gray','Gray'),
        ('clear','Clear'),

        ('olive_green','Olive Green'),
        ('light_sand','Light Sand'),
        # account for light gray, grey
        ('light_gray','Light Gray'),
        # account for coffee
        ('coffee_brown','Coffee Brown'),
    ]
    FABRIC_CHOICES = [
        ('max','Cover MAX'),
        ('tuff','Cover TUFF'),
        ('fab', 'Cover Fab'),
        ('clear', 'Cover Clear'),
    ]
    FABRIC_COST = {
        'max': 10.31,
        'tuff': 12.54,
        'fab': 0.0,
        'clear': 0.0,
    }
    STATUS_CHOICES = [
        ('pending','Pending'),
        ('assigned','Assigned'),
        ('completed','Completed'),
        ('returned','Returned'),
    ]
    RETURN_REMARK_CHOICES = [
        ('', ''),
        ('unprocessed', 'UnProcessed'),
        ('semiprocessed', 'Semi-Processed'),
        ('mistake', 'Cutting Mistake'),
        ('damaged', 'Damaged Goods'),
        ('reject','Rejected'),
        ('rework', 'Re-Worked'),
        ('fault', 'Fault'),
    ]

    class Meta:
        permissions = [
            ('assign_product','Can Assign a worker to product'),
            ('complete_product','Can Complete a product'),
        ]
    objects = ProductQuerySet.as_manager()

    order_number = models.CharField(
        max_length=50,
        default='',
        blank=False,
        verbose_name=_('Order Number'),
        help_text=_('Number of order e.g. COV27622'),
    )
    name = models.CharField(
        max_length=200,
        default='',
        blank=True,
        verbose_name=_('Product Name'),
        help_text=_('Verbose product name as received from supervisor'),
    )
    quantity = models.PositiveSmallIntegerField(
        default=1,
        blank=False,
        verbose_name=_('Quantity (Pcs)'),
        help_text=_('Number of commissions'),
    )
    _size = models.FloatField(
        default=0.0,
        blank=False,
        verbose_name=_('Size (Sq.Ft.)'),
        help_text=_('Total size of product in square feet.'),
    )
    fabric = models.CharField(
        max_length=10,
        choices=FABRIC_CHOICES,
        verbose_name=_('Fabric'),
        help_text=_('Fabric to be used to complete order.'),
    )
    color = models.CharField(
        max_length=50,
        choices=COLOR_CHOICES,
        default='black',
        verbose_name=_('Color'),
        help_text=_('Color of the lot.'),
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='pending',
        verbose_name=_('Status'),
        help_text=_('Status of the Product'),
    )
    dispatched = models.BooleanField(default=False)
    kit = models.ForeignKey(
        'kit.Kit',
        on_delete=models.CASCADE,
        related_name='products',
        help_text=_('Kit that this product belongs to.'),
    )
    challan = models.ForeignKey(
        'challan.Challan',
        null=True,
        default=None,
        blank=True,
        on_delete=models.SET_DEFAULT,
        related_name='products',
        help_text=_('Challan that this product is dispatched through')
    )
    assignedto = models.ForeignKey(
        'worker.Worker',
        on_delete=models.SET_DEFAULT,
        null=True,
        default=None,
        blank=True,
        related_name='products_assigned',
        verbose_name=_('Assigned To'),
        help_text=_('Worker that is assigned to this product'),
    )
    #TODO: change the on_delete so that worker is not deleted if 
    # there are no products completed.
    completedby = models.ForeignKey(
        'worker.Worker',
        on_delete=models.SET_DEFAULT,
        null=True,
        default=None,
        blank=True,
        related_name='products_completed',
        verbose_name=_('Completed By'),
        help_text=_('worker that completed this product'),
    )
    # TODO: add validators so that this date is always >= kit start date
    date_completed = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('Date of Completion'),
        help_text=_('Date at which worker completed with this product in format (YYYY-MM-DD)'),
    )
    date_shipped = models.DateField(
        # auto_now_add=True,
        null=True,
        blank=True,
        verbose_name=_('Shipping Date'),
        help_text=_('Date at which Product is to be shipped to customer in format (YYYY-MM-DD).'),
    )
    #TODO: change the status of the product if return_remark is changed in updateView?
    return_remark = models.CharField(
        max_length=200,
        choices=RETURN_REMARK_CHOICES,
        blank=True,
        default='',
        verbose_name=_('Return Remarks'),
        help_text=_('Select the appropriate remark for returned products'),
    )
    remark = models.CharField(
        max_length=300,
        blank=True,
        default='',
        verbose_name=_('Remark'),
        help_text=_('Additional remark for the Product')
    )
    creation_timestamp = models.DateTimeField(
        auto_now_add=True,
    )

    def __repr__(self):
        return '<Product: {} ({})>'.format(self.order_number, self.id)

    def __str__(self):
        return str(self.order_number)

    def save(self, *args, **kwargs):
        # BUG: This should be removed and added to the views.py in appropriate form.
        self.order_number = self.order_number.upper()
        self.size = round(self.size, 2)
        return super().save(*args, **kwargs)

    def assign(self, worker=None):
        if self.is_dispatched or worker is None:
            return False
        self.assignedto = worker
        self.completedby = None
        self.date_completed = None
        self.return_remark = ''
        self.status = 'assigned'
        self.save()
        return True

    def unassign(self):
        if self.is_assigned:
            self.assignedto = None
            self.status = 'pending'
            self.save()
            return True
        return False

    def complete(self):
        """TODO: refactor the method to use Exceptions"""
        if not self.assignedto or (self.kit.date_product_completion and self.kit.date_product_completion > date.today()):
            return False
        if not self.is_assigned:
            return False
        self.completedby = self.assignedto
        if self.kit.date_product_completion:
            self.date_completed = self.kit.date_product_completion
        else:
            self.date_completed = date.today()
        self.status = 'completed'
        self.save()
        return True

    def uncomplete(self):
        if self.is_dispatched or not self.is_completed:
            return False
        self.completedby = None
        self.date_completed = None
        self.status = 'assigned'
        self.save()
        return True

    def return_product(self, rr=None) -> bool:
        if rr is None or rr not in [i[0] for i in self.RETURN_REMARK_CHOICES]:
            # checking if the input value of rr is valid
            return False
        if self.is_dispatched and rr not in ['reject','rework']:
            # you cannot return a product with un/semi/mistake if product is already dispatched
            return False
        if rr in ['unprocessed','semiprocessed','mistake','damaged']:
            # these return categories are worker independent (i.e. we dnt need the worker
            # infor for these categores) so we uncomplete the product.
            self.uncomplete()
        self.return_remark = rr
        self.status = 'returned'
        self.save()
        return True

    def add_challan(self, challan=None):
        # challan = Challan.objects.get(id=challan_id)
        if self.is_dispatched or challan is None:
            return False
        if not self.is_completed and not self.is_returned:
            return False
        self.challan = challan

challan/views.py
from datetime import date
import requests
import logging
logger = logging.getLogger(__name__)

from django.shortcuts import redirect
from django.core.files import File
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, RedirectView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import DeleteView, UpdateView

from kit.models import Kit
from .models import Challan
from customer.models import Customer
from . import process, excel

class ChallanListView(PermissionRequiredMixin, ListView):
    model = Challan
    navigation = 'challan'
    ordering = ['-number']
    permission_required = ('challan.view_challan')

class ChallanDetailView(PermissionRequiredMixin, DetailView):
    model = Challan
    slug_field = 'number'
    permission_required = ('challan.view_challan','expert.view_product')


class ChallanUpdateView(PermissionRequiredMixin, UpdateView):
    model = Challan
    template_name_suffix = '_update_form'
    fields = [
        'number','date_sent','customer',
        'jobwork_gatepass_processed'
    ]
    permission_required = (
        'challan.view_challan', 'challan.change_challan',
    )

class ChallanPrintableView(PermissionRequiredMixin, DetailView):
    model = Challan
    slug_field = 'number'
    template_name_suffix = '_detail_printable'
    permission_required = ('challan.view_challan','expert.view_product')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        ret = {}
        ret['max'] = {}
        ret['fab'] = {}
        ret['tuff'] = {}
        ret['clear'] = {}
        for fabric in ret:
            ret[fabric] = {
                'quantity': sum([i.quantity for i in self.object.products.filter(fabric=fabric, return_remark='')]),
                'size': round(sum([i.size for i in self.object.products.filter(fabric=fabric, return_remark='')]),2)
            }
        context['groupby_fabric'] = ret
        return context

class ChallanDeleteView(PermissionRequiredMixin, DeleteView):
    model = Challan
    slug_field = 'number'
    success_url = reverse_lazy('challan:list')
    permission_required = ('challan.view_challan','challan.delete_challan')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        """TODO: I shouldnt have to reset the challan foreign key
        it should be done automatically but todo that we have to most probably change
        the on_delete attrib of challan in Product to somethingelse instead of CASCADE
        """
        self.object = self.get_object()
        for product in self.object.products.all():
            product.remove_challan()
        return super().delete(request, *args, **kwargs)

class ChallanCreateRedirectView(PermissionRequiredMixin, SingleObjectMixin, RedirectView):
    model = Kit
    permission_required = ('kit.view_kit','expert.view_product','challan.view_challan','challan.add_challan', 'expert.change_product')

    def _get_challan_number(self):
        if not Challan.objects.all().exists():
            return 51
        else:
            return Challan.objects.all().order_by('-number').first().number + 1

    def get_redirect_url(self, *args, **kwargs):
        kit = self.get_object()
        challan = Challan.objects.create(
            date_sent=date.today(),
            number=self._get_challan_number(),
        )
        for product in kit.products.all():
            product.add_challan(challan)
        challan.date_sent = max([i.date_completed for i in challan.products.all() if i.date_completed])
        # Auto select the default customer and if this doesnt exists 
        # then select the most recently added customer.
        if Customer.objects.exists():
            customer = None
            if Customer.objects.filter(default=True).exists():
                customer = Customer.objects.filter(default=True).first()
            else:
                # selects the most recently added customer
                customer = Customer.objects.all().order_by('-id').first()
            challan.customer = customer
        challan.save()
        return challan.get_absolute_url()


def challan_gatepass(request, pk):
    challan = Challan.objects.get(id=pk)
    img = challan.products.all().first().kit.jobwork_gatepass.url
    print('processing the gatepass image @ {}'.format(img))
    data = {
        'date': challan.date_sent.strftime('%d/%m/%Y'),
        'max_size': str(challan.get_total_size_by_fabric()['max']),
        'tuff_size': str(challan.get_total_size_by_fabric()['tuff']),
        'max_qty': sum([i.quantity for i in challan.products.filter(fabric='max', return_remark='')]),
        'tuff_qty': sum([i.quantity for i in challan.products.filter(fabric='tuff', return_remark='')]),
        'returned_max_size': challan.products.all().returned(fabric='max').size,
        'returned_tuff_size': challan.products.all().returned(fabric='tuff').size,
    }
    _, img = process.main(img, data=data)
    print('Processed gatepass stored @ {}'.format(img))
    with open(img, 'rb') as f:
        challan.jobwork_gatepass_processed.save('gatepass_processed_{}.jpg', File(f))
        challan.save()
    return redirect(challan.jobwork_gatepass_processed.url)

def challan_excel(request, pk):
    challan = Challan.objects.get(pk=pk)
    from django.http import FileResponse
    d, f = excel.main(challan)
    f = open(f, 'rb')
    return FileResponse(f, as_attachment=True, filename='challan_{}_excel.xlsx'.format(challan.number))

challan/templates/challan/challan_detail.html
{% extends 'expert/base.html' %}
{% load static %}

{% block custom_css %}
<style>
    .dropdown:hover > .dropdown-menu {
        /* This is so that the active dropdown-menu doesnt
        become inactive when moving the mouse from top to bottom
        as there is a small space between a.dropdown-toggle and div.dropdown-menu
        this -ve margin will eliminate this space. Go ahead and try this with or without it! */
        margin-top: -1px;
        display: block;
    }
</style>
{% endblock %}

{% block custom_navbar %}
<li class="nav-item">
    <div class="dropdown mr-1">
        <a class="nav-link btn btn-outline-success btn-sm dropdown-toggle" href="#" id="navbarCopyDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-eye"></i> View
        </a>
        <div class="dropdown-menu bg-dark" aria-labelledby="navbarCopyDropdown">
            <a class="text-light dropdown-item" href="{{ challan.get_printable_url }}?param_copy=original">Original Copy</a>
            <a class="text-light dropdown-item" href="{{ challan.get_printable_url }}?param_copy=duplicate">Duplicate Copy</a>
            <a class="text-light dropdown-item" href="{{ challan.get_printable_url }}?param_copy=triplicate">Triplicate Copy</a>
        </div>
    </div>
</li>
<li class="nav-item"><a class="nav-link btn btn-sm btn-outline-primary mr-1" type="button" href="{{ challan.get_update_url }}"><i class="fa fa-pencil"></i> Edit</a></li>
<li class="nav-item"><a class="nav-link btn btn-sm btn-outline-primary mr-1" type="button" href="{{ challan.get_excel_url }}"><i class="fa fa-file-excel-o"></i> Excel</a></li>
{% if challan.jobwork_gatepass_processed %}
<li class="nav-item"><a class="nav-link btn btn-outline-primary btn-sm mr-1" type="button" href="{{ challan.jobwork_gatepass_processed.url }}" target="_blank"><i class="fa fa-download"></i> Gatepass</a> </li>
{% elif challan.products.all.first.kit.jobwork_gatepass %}
<li class="nav-item"><a class="nav-link btn btn-outline-primary btn-sm mr-1" type="button" href="{% url 'challan:gatepass' pk=challan.id %}"><i class="fa fa-tasks"></i> Gatepass</a> </li>
{% endif %}
<li class="nav-item"><a class="nav-link btn btn-outline-danger btn-sm mr-1" type="button" href="{{ challan.get_delete_url }}"><i class="fa fa-ban"></i> Cancel</a> </li>
{% endblock %}

{% block main_content %}
<div class="container py-4 col-11 col-md-9 col-lg-8 col-xl-7">
    <div class="row">
        <div class="col heading h5">
            <div class="text-center">
                Challan #: {{ challan.number }}<br>
                For Ref #. <a href="{{ challan.products.first.kit.get_absolute_url }}">{{ challan.products.first.kit.number }}</a><br>
                For Date: {{ challan.date_sent }}<br>
                To: {{ challan.customer }}
            </div>
        </div>
    </div>
    <div clas="row">
        <div class="list-group">
            {% for product in challan.products.all %}
            <a href="{{ product.get_absolute_url }}" class="font-italic list-group-item list-group-item-action d-flex justify-content-between">
                <span class="font-weight-bold">{{ product.order_number }}</span>
                <span class="text-secondary small">{{ product.date_completed }}</span>
                <span>
                    <span class="badge badge-info badge-pill p-1 px-2">{{ product.size }}</span>
                    {% if product.is_returned %}
                    <span class="badge badge-danger badge-pill p-1 px-2">returned</span>
                    {% else %}
                    <span class="badge badge-primary badge-pill p-1 px-2">{{ product.completedby.username }}</span>
                    {% endif %}
                </span>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

challan/templates/challan/challan_detail_printable.html
{% extends 'expert/base.html' %}
{% load static %}
{% load humanize %}

{# blocks changes so that challan is printed normally without the side navbar interfering #}
{% block custom_js %}
<script>
    $(document).ready(function() {
        $('#main_content').removeClass('col-md-10 col-xl-11 col-9').addClass('col');
        $('#btn-sidebar-expand').hide();
    });
</script>
{% endblock %}

{% block navbar-side %}
<div class="d-none"></div>
{% endblock %}

{% block custom_navbar %}
<!-- <div class="btn-group"> -->
	<li class="nav-item"><a class="nav-link btn btn-outline-primary btn-sm mr-1" type="button" href="javascript:window.print();"><i class="fa fa-print"></i> Print</a></li>
	<li class="nav-item"><a class="nav-link btn btn-outline-secondary btn-sm mr-1" type="button" href="{{ challan.get_absolute_url }}"><i class="fa fa-arrow-left"></i> Back</a></li>
<!-- </div> -->
{% endblock %}

{% block custom_css %}
<style>
    .color-duplicate {
        color: #d63a4f;
    }
    .color-triplicate {
        color: #e3ce30;
    }
    @media print {
        main {
            font-size: 17px;
        }
    }
</style>
{% endblock %}

{% block main_content %}
<div class="container border">
    <div class="row">
        <div class="col-10">
            <center class="h2 mt-1" style="font-size: 2.5rem;">Expert<span><img class="img-fluid" width="60" height="60" src="{% static 'expert/images/logo.png' %}"></span>Traders</center>
            <center class="small">J-142, 1st Floor, Sumel-6, Dhudheshwar, Ahmedabad-380004</center>
            <center class="small"><u>expertcovers2020@gmail.com</u> <b>9839085886</b>, 9660589909</center>
            <center class="small">GSTN: 24AAPPT3833R1ZT</center>
        </div>
    </div>
    <div class="row">
        <div class="col-10 mt-2">
            <center class="h3">Delivery Challan</center>
        </div>
        <div class="col-2">
            <table class="table table-bordered table-sm">
                <tr>
                    <td colspan="2" class="text-center font-weight-bold color-{{ request.GET.param_copy }}">
                        {% if request.GET.param_copy %}
                        {{ request.GET.param_copy|title }}
                        {% else %}
                        Original
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="text-center">{{ challan.date_sent |date:"d.m.Y" }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-7">
            <div class="border">
                Challan No. <b>{{ challan.number }}/20-21</b>
            </div>
            <div class="border">STATE CODE - 24 GUJ.</div>
            <div class="border">
                To, <span class="font-weight-bold">{{ challan.customer.name }}</span> (100% EOU)<br>
                {{ challan.customer.address1 }}, {{ challan.customer.address2 }}<br>
                GSTN No. {{ challan.customer.gstn }} ; IEC : {{ challan.customer.iec }}
            </div>
            <div class="border font-weight-bold">
                FOR REF. No. {{ challan.products.first.kit.number }}/{{ challan.products.first.kit.date_received|date:"d.m.Y" }}
            </div>
        </div>
        <div class="col-5">
            <table class="table table-bordered table-sm">
                <tr>
                    <td>Despatched through</td>
                    <td class="font-weight-bold">Tempo</td>
                </tr>
                <tr>
                    <td>Vehicle No.</td>
                    <td class="font-weight-bold">GJ-18-AU-4157</td>
                </tr>
                <tr>
                    <td>Date/Time</td>
                    <td class="font-weight-bold">{{ challan.date_sent | date:"d.m.Y" }}</td>
                </tr>
                <tr>
                    <td>Destination No.</td>
                    <td class="font-weight-bold">Gandhinagar</td>
                </tr>
                <tr>
                    <td>Invoice No.</td>
                    <td></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-striped">
                <thead>
                    <tr class="text-center">
                        <th>SL</th>
                        <th>Order No.</th>
                        <th>Vendor Name</th>
                        <th>Order Shipping Date</th>
                        <th>Product name</th>
                        <th>Qty</th>
                        <th>Sq.Ft</th>
                        <th>Fabric</th>
                        <th>Color</th>
                        <th>To give Vendor date</th>
                        <th>Target return date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in challan.products.completed %}
                    <tr class="text-center">
                        <td>{{ forloop.counter }}</td>
                        <td>{{ product.order_number }}</td>
                        <td>Dhudheshwar Expert</td>
                        <td>{{ product.date_shipped }}</td>
                        <td>{{ product.name }}</td>
                        <td>{{ product.quantity }}</td>
                        <td>{{ product.size }}</td>
                        <td>{{ product.get_fabric_display }}</td>
                        <td>{{ product.get_color_display }}</td>
                        <td>{{ product.kit.date_received }}</td>
                        <td>{{ product.kit.date_return }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th class="border text-center"><b>{{ challan.quantity }}</b></th>
                        <th class="border text-center"><b>{{ challan.size|intcomma }}</b></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col"></div>
        <div class="col text-center">
            <table class="table table-bordered table-sm">
                <tr>
                    <th>Max</th>
                    <td>{{ groupby_fabric.max.quantity }}</td>
                    <td>{{ groupby_fabric.max.size }}</td>
                </tr>
                <tr>
                    <th>Tuff</th>
                    <td>{{ groupby_fabric.tuff.quantity }}</td>
                    <td>{{ groupby_fabric.tuff.size }}</td>
                </tr>
                <tr>
                    <th>Fab</th>
                    <td>{{ groupby_fabric.fab.quantity }}</td>
                    <td>{{ groupby_fabric.fab.size }}</td>
                </tr>
                <tr>
                    <th>Clear</th>
                    <td>{{ groupby_fabric.clear.quantity }}</td>
                    <td>{{ groupby_fabric.clear.size }}</td>
                </tr>
                <tr>
                    <th>Total</th>
                    <td><b>{{ challan.quantity }}</b></td>
                    <td><b>{{ challan.size|intcomma }}</b></td>
                </tr>
            </table>
        </div>
        <div class="col"></div>
    </div>
    <div class="row mt-4">
        <div class="col-2"></div>
        <div class="col text-center">
            <span>Kit returned due to UnProcessed / Semi-Processed / Cutting Mistake</span>
            <table class="table table-sm table-bordered mt-2">
                {% for product in challan.products.all %}
                {% if product.return_remark %}
                <tr>
                    <td>{{ product.order_number }}</td>
                    <td>{{ product.quantity }}</td>
                    <td>{{ product.size }}</td>
                    <td>{{ product.get_fabric_display }}</td>
                    <td>{{ product.get_color_display }}</td>
                    <td>{{ product.get_return_remark_display }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                <tfoot>
                    <tr>
                        <td></td>
                        <th>{{ challan.return_quantity }}</th>
                        <th>{{ challan.return_size|intcomma }}</th>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
        </div>
        <div class="col-2"></div>
    </div>
    <div class="row mt-4">
        <div class="col">
            <center class="border">Receivers sign and stamp</center>
        </div>
        <div class="col">
            <center class="border">Expert Traders</center>
        </div>
    </div>
    <div class="row mt-3">
        <div class="col text-center small">
            <span>This is a Computer Generated Invoice.</span>
            <span>No Signature Required.</span>
        </div>
    </div>
</div>
{% endblock %}