kit/urls.py
from django.urls import path, include

from . import views

app_name = 'kit'
urlpatterns = [
    path('api/', include('kit.api.urls')),

    path('', views.KitListView.as_view(), name='list'),
    path('create/', views.KitCreateView.as_view(), name='create'),
    path('<slug:slug>/update/', views.KitUpdateView.as_view(), name='update'),
    path('<slug:slug>/view/', views.KitDetailView.as_view(), name='detail'),
    path('<slug:slug>/delete/', views.KitDeleteView.as_view(), name='delete'),
    path('<int:pk>/uncomplete/', views.KitUncompleteRedirectView.as_view(), name='uncomplete'),
    path('<int:pk>/change_completion_date/', views.KitChangeCompletionDate.as_view(), name='change-completion-date'),
]

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('expert.urls')),
    path('kit/', include('kit.urls')),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('invoice/', include('invoice.urls')),
    path('worker/', include('worker.urls')),
    path('challan/', include('challan.urls')),
    path('salary/', include('salary.urls')),
    # path('expert/', include('expert.urls')),
    path('admin/', admin.site.urls),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

worker/api/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.WorkerListAPIView.as_view(), name='api-list'),
    path('<int:pk>/', views.WorkerDetailAPIView.as_view(), name='api-detail'),
]

worker/urls.py
from django.urls import path, include

from . import views

app_name = 'worker'
urlpatterns = [
    path('api/', include('worker.api.urls')),

    path('', views.WorkerListView.as_view(), name='list'),
    path('create/', views.WorkerCreateView.as_view(), name='create'),
    path('<int:pk>/view/', views.WorkerDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.WorkerUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.WorkerDeleteView.as_view(), name='delete'),
] + [
    path('api/<int:pk>/report/', views.WorkerReportView.as_view(), name='api-report')
]

salary/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

from datetime import date
from dateutil.relativedelta import relativedelta as timedelta

# Create your models here.

class SalaryQuerySet(models.QuerySet):
    def active(self):
        pass

class Salary(models.Model):
    date_generated = models.DateField(
        auto_now_add=True,
    )
    worker = models.ForeignKey(
        'worker.Worker',
        on_delete=models.CASCADE,
        related_name='salaries',
    )
    date_from = models.DateField(
        verbose_name=_('From Date'),
    )
    date_to = models.DateField(
        verbose_name=_('To Date'),
    )
    _fixed_rate = models.DecimalField(
        default=0.0,
        max_digits=6,
        decimal_places=2,
        verbose_name=_('Daily Salary'),
        help_text=_('Total Daily salary (without decimal places)'),
    )
    _variable_rate = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        # TODO: retrieve the default rate from settings.
        default=2.5,
        verbose_name=_('SqFt Rate'),
        help_text=_('Rate of the worker per Sq.Ft.'),
    )
    _amount = models.DecimalField(
        default=0.0,
        max_digits=7,
        decimal_places=2,
    )
    objects = SalaryQuerySet.as_manager()

    def get_absolute_url(self):
        return reverse('salary:detail', kwargs={'pk': self.pk})

    @staticmethod
    def get_list_url():
        return reverse('salary:list')

    @staticmethod
    def get_create_url():
        return reverse('salary:create')

    def products(self):
        return self.worker.products_completed.get_date_completed_range(self.date_from, self.date_to).order_by('date_completed')

    @property
    def amount(self):
        ret = 0
        if self.is_fixed:
            days = self.products().dates('date_completed', 'day').count()
            ret = days * self.fixed_rate
        else:
            cs = self.products().completed().size
            rs = self.products().returned().value
            ret = (cs * float(self.variable_rate)) - rs
        return round(ret, 2)

    def get_rate(self):
        if self.is_fixed:
            return '{} / Day'.format(self._fixed_rate)
        else:
            return '{} / Sq.Ft.'.format(self._variable_rate)

    @property
    def variable_rate(self):
        return self._variable_rate

    @property
    def fixed_rate(self):
        return self._fixed_rate

    @property
    def is_fixed(self):
        return self.fixed_rate != 0 and self.variable_rate == 0

worker/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

from datetime import date
from dateutil.relativedelta import relativedelta as timedelta

def worker_image_path(instance, filename):
    return 'Worker/{}/{}'.format(instance.first_name.lower(), filename)

class WorkerQuerySet(models.QuerySet):
    def active(self):
        return self.filter(active=True)

class Worker(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='worker',
        blank=True,
        null=True,
    )
    first_name = models.CharField(
        max_length=100,
        default='',
        blank=False,
    )
    last_name = models.CharField(
        max_length=100,
        default='',
        blank=True,
    )
    _username = models.CharField(
        max_length=100,
        verbose_name=_('Username'),
        default='',
        help_text=_('Username for worker login (unique for each worker)'),
    )
    address = models.TextField(
        default='',
        blank=True,
        help_text=_('Full Address of the worker.'),
    )
    date_joined = models.DateField(
        null=True,
        blank=False,
        verbose_name=_('Joined since'),
        help_text=_('Date of joining.'),
    )
    date_left = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('Date Left'),
        help_text=_('Date at which this worker was fired'),
    )
    # TODO: check if you can retrieve the image of aadhar from aadhar number
    aadhar_number = models.CharField(
        default='',
        blank=True,
        max_length=12,
        verbose_name=_('Aadhar #'),
        help_text=_('Aadhar number of the worker registered. (Enter without any space or delimiter)')
    )
    # TODO: do proper validations for both aadhar and mobile number
    mobile_number = models.CharField(
        default='',
        blank=True,
        max_length=20,
        verbose_name=_('Mobile #'),
        help_text=('10-digit mobile number of the worker without leading zero(s)'),
    )
    fixed_rate = models.DecimalField(
        default=0.0,
        max_digits=6,
        decimal_places=2,
        verbose_name=_('Daily Salary'),
        help_text=_('Total Daily salary (without decimal places)'),
    )
    variable_rate = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        # TODO: retrieve the default rate from settings.
        default=2.5,
        verbose_name=_('SqFt Rate'),
        help_text=_('Rate of the worker per Sq.Ft.'),
    )
    photo = models.ImageField(
        upload_to=worker_image_path,
        null=True,
        blank=True,
        help_text=_('Passport size profile picture for worker.'),
    )
    active = models.BooleanField(
        default=True,
        blank=False,
        verbose_name=_('Is Active?'),
        help_text=_('Is the Worker Active?'),
    )

    class Meta:
        permissions = [
            ('view_profile', 'Worker can view thier own profile'),
        ]
    objects = WorkerQuerySet.as_manager()

    @property
    def fullname(self):
        if self.last_name:
            return '{} {}'.format(self.first_name.capitalize(), self.last_name.capitalize())
        else:
            return self.first_name.capitalize()

    @property
    def username(self):
        return self._username.strip().capitalize() if self._username else ''

    @username.setter
    def username(self, value):
        if self.user:
            self.user.username = value.lower()
            self.user.save()
        self._username = value.lower()
        self.save()

    def get_date_completed_product_range(self, start_date, end_date=None):
        """Get all the products completed by the worker between these dates."""
        if end_date is None:
            end_date = start_date + timedelta(months=1) - timedelta(days=1)
        # TODO: figure out something without having to import kit and products
        ret = self.products_completed.filter(kit__date_received__gte=start_date, kit__date_received__lte=end_date)
        return ret

    def get_total_contribution(self):
        return self.products_completed.all().size

    def get_approx_contribution_badge(self):
        x = self.get_total_contribution()
        if x == 0:
            return 'nil'
        elif x>0 and x<100:
            return '{}+'.format(str(int(x/10)*10))
        elif x>=100 and x<1000:
            return '{}+'.format(str(int(x/100)*100))
        elif x>=1000:
            return '{}+'.format(str(int(x/1000)*1000))

    def get_products_completed_on_date(self, date):
        """Returns all the products completed by this worker on
        a prticular date given.
        """
        return self.products_completed.all().filter(date_completed=date)

    def __repr__(self):
        return '<Worker: {}>'.format(self.username)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('worker:detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('worker:update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('worker:delete', kwargs={'pk': self.pk})

    @staticmethod
    def get_list_url():
        return reverse('worker:list')

    @staticmethod
    def get_create_url():
        return reverse('worker:create')

    def cleanup(self):
        if self.photo:
            self.photo.delete(False)

@receiver(post_save, sender=Worker)
def create_user_for_worker(sender, instance, created, **kwargs):
    # If the user is not defined for the worker and you
    # have included the username in worker then create&update the user.
    if not instance.user and instance.username:
        u = User.objects.create(username=instance.username.lower())
        u.set_password(settings.WORKER_PASSWORD)
        g = Group.objects.get(name='BaseWorkers')
        u.groups.add(g)
        u.save()
        instance.user = u
        instance.save()

worker/api/views.py
from rest_framework import generics

from ..models import Worker
from .serializers import WorkerSerializer

class WorkerListAPIView(generics.ListAPIView):
    queryset = Worker.objects.active()
    serializer_class = WorkerSerializer
    pagination_class = None

class WorkerDetailAPIView(generics.RetrieveAPIView):
    queryset = Worker.objects.all()
    serializer_class = WorkerSerializer

worker/views.py
from datetime import date
from django.shortcuts import redirect
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Worker

import logging
logger = logging.getLogger(__name__)

class WorkerListView(PermissionRequiredMixin, ListView):
    queryset = Worker.objects.filter(active=True).order_by('first_name')
    navigation = 'worker'
    permission_required = ('worker.view_worker')

class WorkerCreateView(PermissionRequiredMixin, CreateView):
    model = Worker
    fields = [
        'first_name','last_name','_username','address',
        'date_joined','photo',
    ]
    template_name_suffix = '_create_form'
    permission_required = ('worker.view_worker','worker.add_worker')

    def form_valid(self, form):
        form.instance._username = form.instance._username.lower()
        return super().form_valid(form)

class WorkerDetailView(PermissionRequiredMixin, DetailView):
    model = Worker
    permission_required = ('worker.view_worker')

    def has_permission(self):
        """Give the permission for a user to access his/her own page"""
        ret = super().has_permission()
        return ret or self.request.user.worker.pk == self.kwargs['pk']

    def get_context_data(self, **kwargs):
        kwargs['product_list'] = self.object.products_completed.order_by(
            '-kit__number', '-date_completed'
        )
        return super().get_context_data(**kwargs)

class WorkerReportView(PermissionRequiredMixin, View):
    permission_required = ('worker.view_worker')

    def has_permission(self):
        ret = super().has_permission()
        return ret or self.request.user.worker.pk == self.kwargs['pk']

    def get(self, *args, **kwargs):
        worker = Worker.objects.get(pk=self.kwargs['pk'])
        date_from = date.fromisoformat(self.request.GET.get('date_from', str(worker.date_joined)))
        date_to = date.fromisoformat(self.request.GET.get('date_to', str(date.today())))
        ptype = self.request.GET.get('type', 'all')
        print(date_from, date_to)
        data = []
        plist = worker.products_completed.get_date_completed_range(date_from, date_to)
        if ptype == 'dispatched':
            plist = plist.dispatched()
        elif ptype == 'remaining':
            plist = plist.remaining()
        elif ptype == 'completed':
            plist = plist.completed()
        elif ptype == 'returned':
            plist = plist.returned()
        for i in plist:
            data.append([
                i.kit.number,
                i.order_number,
                i.date_completed.strftime('%b %d, %Y'),
                i.quantity,
                i.size,
                i.get_return_remark_display() if i.is_returned else i.get_status_display(),
                i.remark
            ])
        return JsonResponse({'data': data})

class WorkerUpdateView(PermissionRequiredMixin, UpdateView):
    model = Worker
    fields = [
        'first_name','last_name','_username','address',
        'date_joined','photo', 'fixed_rate', 'variable_rate',
    ]
    template_name_suffix = '_update_form'
    permission_required = ('worker.view_worker','worker.change_worker')

    def form_valid(self, form):
        form.instance._username = form.instance._username.lower()
        return super().form_valid(form)

class WorkerDeleteView(PermissionRequiredMixin, DeleteView):
    model = Worker
    success_url = reverse_lazy('worker:list')
    permission_required = ('worker.view_worker','worker.delete_worker')

    def delete(self, request, *args, **kwargs):
        """
        Overwriting the delete method because once a worker is created
        it should not be deleted.
        only it should be rendered inactive.
        """
        self.object = self.get_object()
        logger.info('Deleting the Worker: {}'.format(self.object.username))
        success_url = self.get_success_url()
        self.object.active = False
        self.object.save()
        return redirect(success_url)

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

worker/templates/worker/worker_create_form.html
{% extends 'expert/base.html' %}
{% load static %}
{% load add_attr %}

{% block custom_js %}
<script>
	$(document).ready(function() {
		$('#btn-save').on('click', function(e) {
			e.preventDefault();
			$('#btn-submit').click();
		});
		$('#id__username').change(function() {
			let username = $(this).val();
			let $this = $(this);
			$.ajax({
				url: "{% url 'expert:validate-create-worker-username' %}",
				dataType: "json",
				data: {
					'username': username
				},
				success: function(result) {
					if (result.is_taken) {
						$this.addClass('border border-danger');
						alert('A worker with this Username already exists');
					}
					else {
						$this.removeClass('border border-danger');
					}
				}
			});
			console.log($(this).val());
		});
	});
</script>
{% endblock %}

{% block custom_navbar %}
<li class="nav-item"><a class="nav-link btn btn-success btn-sm mr-1" type="button" href="" id="btn-save"><i class="fa fa-floppy-o"></i> Save</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-secondary btn-sm mr-1" type="button" href="{{ Worker.get_list_url }}"><i class="fa fa-arrow-left"></i> Back</a></li>
{% endblock %}

{% block main_content %}
<div class="container d-flex justify-content-center col-11 col-md-9 col-lg-8 col-xl-7">
	<div class="col">
		<div class="heading text-center my-4 h3">Create New Worker</div>
		<form method="post" enctype="multipart/form-data" autocomplete="off">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group row">
				<label for="{{ field.id_for_label }}" class="col-4 col-form-label">{{ field.label }}</label>
				<div class="col-8">
					{{ field|add_attr:"form-control" }}
					{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
					{% endif %}
				</div>
			</div>
			{% endfor %}
			<div class="form-group row d-flex justify-content-center">
				<button type="submit" class="btn btn-outline-success w-50 d-none" id="btn-submit">Update</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}

worker/templates/worker/worker_detail.html
{% extends 'expert/base.html' %}
{% load static %}

{% block custom_navbar %}
<li class="nav-item"><a class="nav-link btn btn-outline-info btn-sm mr-1" type="button" href="{{ Salary.get_list_url }}?worker_pk={{ worker.pk }}"><i class="fa fa-money"></i> Salary</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-success btn-sm mr-1" type="button" href="{{ Salary.get_create_url }}?worker_pk={{ worker.pk }}"><i class="fa fa-plus"></i> Add New</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-primary btn-sm mr-1" type="button" href="{{ worker.get_update_url }}"><i class="fa fa-pencil"></i> Edit</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-danger btn-sm mr-1" type="button" href="{{ worker.get_delete_url }}"><i class="fa fa-trash"></i> Delete</a></li>
{% endblock %}

{% block custom_js %}
<script>
	function getTableURL(date_from, date_to, type) {
		return("{% url 'worker:api-report' pk=worker.pk %}?date_from="+date_from+"&date_to="+date_to+"&type="+type);
	}
	var table;
	$(document).ready(function() {
		var date_from="2020-05-01", date_to="2020-05-01", type="all";
		$('#id_date_from').change(function() {
			date_from = $(this).val();
			table.ajax.url(getTableURL(date_from, date_to, type)).load();
		});
		$('#id_date_to').change(function() {
			date_to = $(this).val();
			table.ajax.url(getTableURL(date_from, date_to, type)).load();
		});
		$('#id_type').change(function() {
			type = $(this).val();
			table.ajax.url(getTableURL(date_from, date_to, type)).load();
		})
		table = $('#worker-detail-table').DataTable({
			'ajax': {
				'url': getTableURL(date_from, date_to, type),
			},
			'drawCallback': function(settings) {
				var api = this.api();
				var data = api.rows().data();
				var total_qty=0, total_size=0;
				if (data.length > 0) {
					for (var i=0; i<data.length; i++) {
						total_qty += data[i][3];
						total_size += data[i][4];
					}
					$('#worker-detail-table tfoot .quantity').html(total_qty);
					total_size = Math.round((total_size + Number.EPSILON)*100) / 100;
					$('#worker-detail-table tfoot .size').html(total_size);
				}
			},
			'createdRow': function(row, data, index) {
				// made the first col of the table (kit number)
				// clickable and pointing to the kit detail view
				$('td', row).eq(0).addClass('clickable');
				$('td', row).eq(0).on('click', function(e) {
					location.href = "/kit/"+data[0]+"/view/";
				});
				// the 5th col is the status col
				if (data[5] == "Completed") {
					$('td', row).eq(5).addClass('completed');
				}
				else {
					$('td', row).eq(5).addClass('returned');
				}
			}
		});
	});
</script>
{% endblock %}

{% block custom_css %}
<style>
	td.clickable {
		cursor: pointer;
	}
	td.clickable:hover {
		font-weight: bold;
		font-size: 1.1em;
		background-color: whitesmoke;
	}
	td.completed, td.returned {
		color: white;
		text-align: center;
	}
	td.completed {
		background-color: green;
	}
	td.returned {
		background-color: red;
	}
</style>
{% endblock %}

{% block main_content %}
<div class="container">
	<div class="row py-4">
		<div class="col-6">
			<div class="image_container">
				{% if worker.photo %}
				<img class="img-fluid" alt="worker photo" src="{{ worker.photo.url }}" width="200" height="200">
				{% else %}
				<img class="img-fluid" src="{% static 'expert/images/default_user_image.jpg' %}" width="200" height="200">
				{% endif %}
			</div>
		</div>
		<div class="col-6">
			<span class="h3">{{ worker.fullname }}</span>
			<br>
			<small>Joined since - {{ worker.date_joined }}</small>
			<br>
			<span>{{ worker.address }}</span>
			<br>
			{% if worker.aadhar_number %}
			<span>Aadhar Number -- {{ worker.aadhar_number }}</span>
			{% endif %}
			<br>
			{% if worker.mobile_number %}
			<span><i class="fa fa-mobile"></i> Mobile -- {{ worker.mobile_number }}</span>
			<br>
			{% endif %}
			<!-- {% if worker.fixed_rate %}
			<br>
			<span>Fixed Rate -- <i class="fa fa-inr"></i>{{ worker.fixed_rate }} / Month</span>
			{% else %}
			<br>
			<span>Rate -- <i class="fa fa-inr"></i>{{ worker.variable_rate }} / Sq.Ft.</span>
			{% endif %} -->
		</div>
	</div>
	<div class="row">
		<div class="col">
			<div class="my-3">
				<input type="text" class="form-control col-3 d-inline" id="id_date_from" placeholder="From Date">
				<input type="text" class="form-control col-3 d-inline" id="id_date_to" placeholder="To Date">
				<select class="form-control col-3 d-inline" id="id_type">
					<option value="all">All</option>
					<option value="dispatched">Dispatched</option>
					<option value="remaining">Remaining</option>
					<option value="completed">Completed</option>
					<option value="returned">Returned</option>
				</select>
			</div>
			<div>
				<table class="table table-hover table-sm table-bordered table-striped" id="worker-detail-table">
					<thead>
						<tr>
							<th>#</th>
							<th>Product #</th>
							<th>Date</th>
							<th>Qty</th>
							<th>Sq.Ft.</th>
							<th>Status</th>
							<th>Remark</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>#</th>
							<th>Product #</th>
							<th>Date</th>
							<th class="quantity">Qty</th>
							<th class="size">Sq.Ft.</th>
							<th class="status">Status</th>
							<th class="remark">Remark</th>
						</tr>
					</tfoot>
				</table>
			</div>
		</div>
	</div>
</div>
{% endblock %}

worker/templates/worker/worker_list.html
{% extends 'expert/base.html' %}
{% load static %}

{% block custom_js %}
<script>
	$(function() {
		var table = $('#table-worker-list').DataTable({
			'ordering': false,
			'conditionalPaging': true,
			'searching': false,
			"fnDrawCallback": function(settings) {
				$(settings.nTHead).hide();
			},
			dom: '<"float-right"B>ltip',
			buttons: [{
				text: '<i class="fa fa-plus"></i> Add New',
				className: 'btn btn-primary btn-sm font-italic',
				action: function(e, dt, node, config) {
					window.location.href = "{{ Worker.get_create_url }}";
				}
			}],
		});

		$('#table-worker-list tbody').on('click', 'tr', function() {
			var url = $(this).attr('data-href');
			window.location.href = url;
		})
	});
</script>
{% endblock %}

{% block custom_css %}
<style>
	ul.pagination > .paginate_button {
		padding: 4px 2px!important;
	}
</style>
{% endblock %}

{% block main_content %}
<div class="container py-0 col-11 col-md-9 col-lg-8 col-xl-6">
	<div class="px-3 h2 text-center m-0 py-1">
		List of StitchMen
	</div>
	<div class="row mt-2">
		<div class="col font-italic">
			<table class="hover display row-border table-datatable" id="table-worker-list">
				<thead>
					<tr>
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					{% for worker in worker_list %}
					<tr data-href="{{ worker.get_absolute_url }}">
						<td class="font-weight-bold text-left">
							<span class="mr-2 pr-2 border-right border-dark">{{ forloop.counter }}</span>{{ worker.username }}
						</td>
						<td class="text-right">
							<span class="badge badge-success badge-pill">{{ worker.get_approx_contribution_badge }}</span>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

worker/templates/worker/worker_update_form.html
{% extends 'expert/base.html' %}
{% load static %}
{% load add_attr %}

{% block custom_js %}
<script>
	$(document).ready(function() {
		$('#btn-update').on('click', function(e) {
			e.preventDefault();
			$('#btn-submit').click();
		});
	});
</script>
{% endblock %}

{% block custom_navbar %}
<li class="nav-item"><a class="nav-link btn btn-success btn-sm mr-1" type="button" href="" id="btn-update"><i class="fa fa-pencil-square-o"></i> Update</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-secondary btn-sm mr-1" type="button" href="{{ worker.get_absolute_url }}"><i class="fa fa-arrow-left"></i> Back</a></li>
{% endblock %}

{% block main_content %}
<div class="container d-flex justify-content-center col-11 col-md-9 col-lg-8 col-xl-7">
	<div class="col">
		<div class="heading text-center my-4 h3">Update StitchMan</div>
		<form method="post" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
			<div class="form-group row">
				<label for="{{ field.id_for_label }}" class="col-4 col-form-label">{{ field.label }}</label>
				<div class="col-8">
                    {% if field.errors %}
                    <small class="form-text text-danger font-weight-bold">{{ field.errors }}</small>
                    {{ field|add_attr:"form-control border border-danger" }}
                    {% else %}
					{{ field|add_attr:"form-control" }}
                    {% endif %}
					{% if field.help_text %}
					<small class="form-text text-muted">{{ field.help_text }}</small>
					{% endif %}
				</div>
			</div>
			{% endfor %}
			<div class="form-group row d-flex justify-content-center">
				<button type="submit" class="btn btn-outline-success w-50 d-none" id="btn-submit">Update</button>
			</div>
		</form>
	</div>
</div>
{% endblock %}