challan/urls.py
from django.urls import path

from . import views

app_name = 'challan'
urlpatterns = [
    path('', views.ChallanListView.as_view(), name='list'),
    path('<slug:slug>/view/', views.ChallanDetailView.as_view(), name='detail'),
    path('<int:pk>/create/', views.ChallanCreateRedirectView.as_view(), name='create'),
    path('<slug:slug>/view/printable/', views.ChallanPrintableView.as_view(), name='printable'),
    path('<slug:slug>/delete/', views.ChallanDeleteView.as_view(), name='delete'),
    path('<int:pk>/update/', views.ChallanUpdateView.as_view(), name='update'),
    # url loading the gatepass 
    path('<int:pk>/gatepass/', views.challan_gatepass, name='gatepass'),
    path('<int:pk>/excel/', views.challan_excel, name='excel'),
]

kit/api/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.KitListAPIView.as_view(), name='api-list'),
    path('<int:pk>/', views.KitDetailAPIView.as_view(), name='api-detail'),
]

kit/urls.py
from django.urls import path, include

from . import views

app_name = 'kit'
urlpatterns = [
    path('api/', include('kit.api.urls')),

    path('', views.KitListView.as_view(), name='list'),
    path('create/', views.KitCreateView.as_view(), name='create'),
    path('<slug:slug>/update/', views.KitUpdateView.as_view(), name='update'),
    path('<slug:slug>/view/', views.KitDetailView.as_view(), name='detail'),
    path('<slug:slug>/delete/', views.KitDeleteView.as_view(), name='delete'),
    path('<int:pk>/uncomplete/', views.KitUncompleteRedirectView.as_view(), name='uncomplete'),
    path('<int:pk>/change_completion_date/', views.KitChangeCompletionDate.as_view(), name='change-completion-date'),
]

product/urls.py
from django.urls import path, include

from . import views

app_name = 'product'
urlpatterns = [
    path('api/', include('product.api.urls')),

    path('<int:pk>/update/', views.ProductUpdateView.as_view(), name='update'),
    path('create/<int:kit_number>/', views.ProductCreateView.as_view(), name='create'),
    path('<int:pk>/delete/', views.ProductDeleteView.as_view(), name='delete'),
    path('<int:pk>/view/', views.ProductDetailView.as_view(), name='detail'),
    path('<int:pk>/return/', views.ProductReturnRedirectView.as_view(), name='return'),
    path('<int:pk>/split/', views.ProductSplitRedirectView.as_view(), name='split'),
]

website/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('expert.urls')),
    path('kit/', include('kit.urls')),
    path('product/', include('product.urls')),
    path('customer/', include('customer.urls')),
    path('invoice/', include('invoice.urls')),
    path('worker/', include('worker.urls')),
    path('challan/', include('challan.urls')),
    path('salary/', include('salary.urls')),
    # path('expert/', include('expert.urls')),
    path('admin/', admin.site.urls),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kit/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from datetime import date
from dateutil.relativedelta import relativedelta as timedelta

from product.models import Product

def kit_image_path(instance, filename):
    # return 'Kit_{}/Images/{}'.format(instance.number, filename)
    return 'Kit/{}/Images/{}'.format(instance.number, filename)

class KitQuerySet(models.QuerySet):
    def get_date_received_range(self, start_date, end_date=None):
        if end_date is None:
            end_date = start_date + timedelta(months=1) - timedelta(days=1)
        return self.filter(date_received__lte=end_date, date_received__gte=start_date)

    def products(self):
        # TODO: make some other representation so that we dont hve to import Product
        return Product.objects.filter(kit__in=self.all())

class Kit(models.Model):
    """Container for model that represents the KIT that is sent each day"""
    STATUS_CHOICES = [
        ('pending','Pending'),
        ('working','Working'),
        ('completed','Completed'),
        ('dispatched','Dispatched'),
    ]

    number = models.PositiveSmallIntegerField(
        default=1,
        blank=False,
        unique=True,
        verbose_name=_('Kit Number'),
        help_text=_('Unique number of kit from delivery challan.'),
    )
    status = models.CharField(
        max_length=50,
        choices=STATUS_CHOICES,
        default='pending',
        verbose_name=_('Status'),
        help_text=_('Status of the Kit'),
    )
    date_received = models.DateField(
        # auto_now_add=True,
        null=True,
        blank=True,
        verbose_name=_('Date Received'),
        help_text=_('Date at which KIT is received in format (YYYY-MM-DD).'),
    )
    date_return = models.DateField(
        # auto_now_add=True,
        null=True,
        blank=True,
        verbose_name=_('Expected Return Date'),
        help_text=_('Date at which KIT is expected to be returned in format (YYYY-MM-DD).'),
    )
    date_product_completion = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('Product Completion Date'),
        help_text=_('Manual Date which can be set so that all the products \
            in this kit will be completed on this date')
    )
    data = models.TextField(
        blank=True,
        default='',
        verbose_name=_('Excel Data'),
        help_text=_('Copy paste the excel rows containing the product data'),
    )
    original_kit_summary = models.ImageField(
        upload_to=kit_image_path,
        null=True,
        blank=True,
        verbose_name=_('Original KIT Image'),
        help_text=_('Upload the jpg of the original/unmodified image of kit summary'),
    )
    jobwork_challan = models.ImageField(
        upload_to=kit_image_path,
        null=True,
        blank=True,
        verbose_name=_('Jobwork Challan Image'),
        help_text=_('Upload the jpg/png image of the jobwork challan that came with kit.'),
    )
    ewaybill = models.ImageField(
        upload_to=kit_image_path,
        null=True,
        blank=True,
        verbose_name=_('E-Way Bill'),
        help_text=_('GSTN E-Way Bill that came with the kit'),
    )
    jobwork_gatepass = models.ImageField(
        upload_to=kit_image_path,
        null=True,
        blank=True,
        verbose_name=_('Jobwork Gate Pass'),
        help_text=_('Upload the original jpg/png of the jobwork gatepass that came with kit'),
    )

    objects = KitQuerySet.as_manager()

    def __repr__(self):
        return '<Kit: {}>'.format(str(self.number))

    def __str__(self):
        return str(self.number)

    @staticmethod
    def get_list_url():
        return reverse('kit:list')

    @staticmethod
    def get_create_url():
        return reverse('kit:create')

    def get_absolute_url(self):
        return reverse(
            'kit:detail',
            kwargs={
                'slug': self.number
            }
        )

    def get_update_url(self):
        return reverse('kit:update', kwargs={'slug': self.number})

    def get_delete_url(self):
        return reverse('kit:delete', kwargs={'slug': self.number})

    def get_uncomplete_url(self):
        return reverse('kit:uncomplete', kwargs={'pk': self.pk})

    def get_change_completion_date_url(self):
        return reverse('kit:change-completion-date', kwargs={'pk': self.pk})
    
    @staticmethod
    def get_all():
        return Kit.objects.all()

    @property
    def size(self):
        return self.products.all().size

    @property
    def quantity(self):
        return self.products.all().quantity

    # @property
    # def quantity_detail(self):
    #     # pending = sum([i.quantity for i in self.products.pending()])
    #     # completed = sum([i.quantity for i in self.products.completed()])
    #     # assigned = sum([i.quantity for i in self.products.assigned()])
    #     # returned = sum([i.quantity for i in self.products.returned()])
    #     # dispatched = sum([i.quantity for i in self.products.dispatched()])
    #     ret = {
    #         'pending': self.products.pending().quantity,
    #         'assigned': self.products.assigned().quantity,
    #         'completed': self.products.completed().dispatched().quantity,
    #         'returned': self.products.returned().dispatched().quantity,
    #         'dispatched': self.products.dispatched().quantity,
    #     }
    #     return ret

    # @property
    # def size_detail(self):
    #     # pending = sum([i.size for i in self.products.pending()])
    #     # completed = sum([i.size for i in self.products.completed()])
    #     # assigned = sum([i.size for i in self.products.assigned()])
    #     # returned = sum([i.size for i in self.products.returned()])
    #     # dispatched = sum([i.size for i in self.products.dispatched()])
    #     ret = {
    #         'pending': self.products.pending().size,
    #         'assigned': self.products.assigned().size,
    #         'completed': self.products.completed().dispatched().size,
    #         'returned': self.products.returned().dispatched().size,
    #         'dispatched': self.products.dispatched().size,
    #     }
    #     return ret

worker/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings

from datetime import date
from dateutil.relativedelta import relativedelta as timedelta

def worker_image_path(instance, filename):
    return 'Worker/{}/{}'.format(instance.first_name.lower(), filename)

class WorkerQuerySet(models.QuerySet):
    def active(self):
        return self.filter(active=True)

class Worker(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='worker',
        blank=True,
        null=True,
    )
    first_name = models.CharField(
        max_length=100,
        default='',
        blank=False,
    )
    last_name = models.CharField(
        max_length=100,
        default='',
        blank=True,
    )
    _username = models.CharField(
        max_length=100,
        verbose_name=_('Username'),
        default='',
        help_text=_('Username for worker login (unique for each worker)'),
    )
    address = models.TextField(
        default='',
        blank=True,
        help_text=_('Full Address of the worker.'),
    )
    date_joined = models.DateField(
        null=True,
        blank=False,
        verbose_name=_('Joined since'),
        help_text=_('Date of joining.'),
    )
    date_left = models.DateField(
        null=True,
        blank=True,
        verbose_name=_('Date Left'),
        help_text=_('Date at which this worker was fired'),
    )
    # TODO: check if you can retrieve the image of aadhar from aadhar number
    aadhar_number = models.CharField(
        default='',
        blank=True,
        max_length=12,
        verbose_name=_('Aadhar #'),
        help_text=_('Aadhar number of the worker registered. (Enter without any space or delimiter)')
    )
    # TODO: do proper validations for both aadhar and mobile number
    mobile_number = models.CharField(
        default='',
        blank=True,
        max_length=20,
        verbose_name=_('Mobile #'),
        help_text=('10-digit mobile number of the worker without leading zero(s)'),
    )
    fixed_rate = models.DecimalField(
        default=0.0,
        max_digits=6,
        decimal_places=2,
        verbose_name=_('Daily Salary'),
        help_text=_('Total Daily salary (without decimal places)'),
    )
    variable_rate = models.DecimalField(
        max_digits=4,
        decimal_places=2,
        # TODO: retrieve the default rate from settings.
        default=2.5,
        verbose_name=_('SqFt Rate'),
        help_text=_('Rate of the worker per Sq.Ft.'),
    )
    photo = models.ImageField(
        upload_to=worker_image_path,
        null=True,
        blank=True,
        help_text=_('Passport size profile picture for worker.'),
    )
    active = models.BooleanField(
        default=True,
        blank=False,
        verbose_name=_('Is Active?'),
        help_text=_('Is the Worker Active?'),
    )

    class Meta:
        permissions = [
            ('view_profile', 'Worker can view thier own profile'),
        ]
    objects = WorkerQuerySet.as_manager()

    @property
    def fullname(self):
        if self.last_name:
            return '{} {}'.format(self.first_name.capitalize(), self.last_name.capitalize())
        else:
            return self.first_name.capitalize()

    @property
    def username(self):
        return self._username.strip().capitalize() if self._username else ''

    @username.setter
    def username(self, value):
        if self.user:
            self.user.username = value.lower()
            self.user.save()
        self._username = value.lower()
        self.save()

    def get_date_completed_product_range(self, start_date, end_date=None):
        """Get all the products completed by the worker between these dates."""
        if end_date is None:
            end_date = start_date + timedelta(months=1) - timedelta(days=1)
        # TODO: figure out something without having to import kit and products
        ret = self.products_completed.filter(kit__date_received__gte=start_date, kit__date_received__lte=end_date)
        return ret

    def get_total_contribution(self):
        return self.products_completed.all().size

    def get_approx_contribution_badge(self):
        x = self.get_total_contribution()
        if x == 0:
            return 'nil'
        elif x>0 and x<100:
            return '{}+'.format(str(int(x/10)*10))
        elif x>=100 and x<1000:
            return '{}+'.format(str(int(x/100)*100))
        elif x>=1000:
            return '{}+'.format(str(int(x/1000)*1000))

    def get_products_completed_on_date(self, date):
        """Returns all the products completed by this worker on
        a prticular date given.
        """
        return self.products_completed.all().filter(date_completed=date)

    def __repr__(self):
        return '<Worker: {}>'.format(self.username)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('worker:detail', kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('worker:update', kwargs={'pk': self.pk})

    def get_delete_url(self):
        return reverse('worker:delete', kwargs={'pk': self.pk})

    @staticmethod
    def get_list_url():
        return reverse('worker:list')

    @staticmethod
    def get_create_url():
        return reverse('worker:create')

    def cleanup(self):
        if self.photo:
            self.photo.delete(False)

@receiver(post_save, sender=Worker)
def create_user_for_worker(sender, instance, created, **kwargs):
    # If the user is not defined for the worker and you
    # have included the username in worker then create&update the user.
    if not instance.user and instance.username:
        u = User.objects.create(username=instance.username.lower())
        u.set_password(settings.WORKER_PASSWORD)
        g = Group.objects.get(name='BaseWorkers')
        u.groups.add(g)
        u.save()
        instance.user = u
        instance.save()

kit/api/views.py
from rest_framework import generics

from ..models import Kit
from .serializers import KitSerializer

class KitListAPIView(generics.ListAPIView):
    queryset = Kit.objects.all()
    serializer_class = KitSerializer

class KitDetailAPIView(generics.RetrieveAPIView):
    queryset = Kit.objects.all()
    serializer_class = KitSerializer

kit/templates/kit/kit_detail_react.html
{% extends 'expert/base.html' %}
{% load static %}
{% load humanize %}
{% load url_replace %}

{% block custom_css %}
<style>
	.product-fabric {
		text-transform: capitalize;
	}
	.dot {
		width:17px;
		height: 17px;
		background-color: black;
		border-radius: 50%;
		display: inline-block;
	}
	.product-color {
		text-align: left;
		text-transform: capitalize;
		padding-left: 1.5rem !important;
	}
	.product-color > span {
		margin-right: .25rem;
	}
	.color-gray {background-color: gray;}
    .color-black {background-color: black;}
    .color-beige {background-color: #E1C699;}
    .color-blue {background-color: blue;}
    .color-white {background-color: white;}
    .color-brown {background-color: brown;}
    .color-green {background-color: green;}
    .color-sand {background-color: yellow;}
    .color-gray {background-color: gray;}
    .color-olive_green {background-color: #556b2f;}
    .color-light_sand {background-color: #c2b280;}
    .color-light_gray {background-color: lightgray;}
    .color-coffee_brown {background-color: #4a2c2a;}
    .color-burgundy {background-color: #800020;}
	.color-clear {background-color: clear;}

	.product-status {
		text-transform: capitalize;
	}

	table tbody td {
		vertical-align: middle !important;
	}
	#product-table thead .dropdown-toggle::after {
		content: none;
	}

	#returndropdownbutton:after, #splitdropdownbutton:after {
		content: none;
	}

	.scrollable-dropdown-menu {
		height: auto;
		max-height: 250px;
		overflow-x: hidden;
	}

	@media print {
		main {
			font-size: 17px;
		}
		#btn-sidebar-collapse, #btn-sidebar-expand,
		#product-table tbody tr td:last-child, 
		#product-table thead tr th:last-child,
		.table-header > div {
			display: none;
		}
		#product-table tbody td.status {
			background-color: transparent;
			color: black!important;
		}
		#product-table td.assignedto button {
			border: none;
		}
		#product-table td.assignedto button::after {
			content: none;
		}
	}
</style>
{% endblock %}

{% block custom_js %}
<script>
$(document).ready(function() {

});
</script>
<script type="text/babel" src="{% static 'kit/js/react_kit_detail.js' %}"></script>
{% endblock %}

{% block custom_navbar %}
<li class="nav-item"><a class="nav-link btn btn-outline-primary btn-sm mr-1" type="button" href="{{ kit.get_update_url }}"><i class="fa fa-pencil"></i> Edit</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-danger btn-sm mr-1" type="button" href="{{ kit.get_delete_url }}"><i class="fa fa-trash"></i> Delete</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-info btn-sm mr-1" type="button" href="{% url 'product:create' kit_number=kit.number %}"><i class="fa fa-plus"></i> Add New</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-success btn-sm mr-1" type="button" href="{% url 'challan:create' pk=kit.id %}">Make Challan</a></li>
<li class="nav-item"><a class="nav-link btn btn-outline-warning btn-sm mr-1" {% if kit.get_completed_quantity == 0 %}disbaled{% endif %} type="button" href="{{ kit.get_uncomplete_url }}"><i class="fa fa-ban"></i> Uncomplete</a></li>
{% endblock %}

{% block main_content %}
<div class="container-fluid">
	<div id="root" data-url="{% url 'kit:api-detail' pk=kit.pk %}"></div>
</div>
{% endblock %}
<div class="container-fluid">
	<div class="heading text-center h3 mt-1 mb-0 pb-0">Overview of LOT {{ kit.number }}</div>
	<div class="text-center small">{{ kit.date_received }} ({{ kit.date_return }})</div>
	<div class="table-responsive">
		<div class="d-flex table-header">
			<div class="mr-auto text-muted">
				Product Completion Date -
				<span class="font-weight-bold">
					{% if kit.date_product_completion %}
					{{ kit.date_product_completion }}
					{% else %}
					{% now "N j, Y" %}
					{% endif %}
				</span>
				<input type="hidden" id="datepicker_product_completion" data-href="{{ kit.get_change_completion_date_url }}">
			</div>
			<div style="color: #333;">
				Show
				<select class="custom-select custom-select-sm form-control form-control-sm w-auto" id="dropdownnumberrecords">
					<option value="10">10</option>
					<option value="25">25</option>
					<option value="50">50</option>
					<option value="100">100</option>
				</select>
				entries
			</div>
		</div>
		<table class="table table-sm table-hover table-striped text-center" id="product-table">
			<thead class="bg-dark text-light font-weight-bold">
				<tr>
					<th class="text-left">Order #</th>
					<th>Qty</th>
					<th>Sq.Ft.</th>
					<th>
						<div class="dropdown d-inline">
							<button class="p-0 m-0 ml-1 dropdown-toggle bg-transparent border-0 text-light font-weight-bold" type="button" id="dropdownstatussort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Fabric<i class="fa fa-filter ml-2"></i>
							</button>
							<div class="dropdown-menu" aria-labelledby="dropdownstatussort">
								<a class="dropdown-item" href="?{% url_replace filters='' page=1 %}">All</a>
								<a class="dropdown-item" href="?{% url_replace filters='fabric:max' page=1 %}">Max</a>
								<a class="dropdown-item" href="?{% url_replace filters='fabric:tuff' page=1 %}">Tuff</a>
								<a class="dropdown-item" href="?{% url_replace filters='fabric:fab' page=1 %}">Fab</a>
								<a class="dropdown-item" href="?{% url_replace filters='fabric:clear' page=1 %}">Clear</a>
							</div>
						</div>
					</th>
					<th class="text-left pl-5">Color</th>
					<th>Assigned To</th>
					<th>Completed By</th>
					<th>Completion Date</th>
					<th>
						<div class="dropdown d-inline">
							<button class="p-0 m-0 ml-1 dropdown-toggle bg-transparent border-0 text-light font-weight-bold" type="button" id="dropdownstatussort" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								Status<i class="fa fa-filter ml-2"></i>
							</button>
							<div class="dropdown-menu" aria-labelledby="dropdownstatussort">
								<a class="dropdown-item" href="?{% url_replace filters='' page=1 %}">All</a>
								<a class="dropdown-item" href="?{% url_replace filters='status:pending' page=1 %}">Pending</a>
								<a class="dropdown-item" href="?{% url_replace filters='status:assigned' page=1 %}">Assigned</a>
								<a class="dropdown-item" href="?{% url_replace filters='status:completed' page=1 %}">Completed</a>
								<a class="dropdown-item" href="?{% url_replace filters='status:dispatched' page=1 %}">Dispatched</a>
								<a class="dropdown-item" href="?{% url_replace filters='status:returned' page=1 %}">Returned</a>
							</div>
						</div>
					</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for product in product_list %}
				<tr class="">
					<td class="text-left font-italic"><a href="{{ product.get_absolute_url }}">{{ product.order_number }}</a></td>
					<td>{{ product.quantity }}</td>
					<td>{{ product.size }}</td>
					<td>{{ product.get_fabric_display }}</td>
					<td class="text-left pl-4"><span class="dot color-{{ product.color }} align-middle"></span> {{ product.get_color_display }}</td>
					<td class="assignedto">
						<div class="dropdown">
							<button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton-{{ product.id }}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								{% if product.is_pending %}
								Assign To
								{% else %}
								{{ product.assignedto.username }}
								{% endif %}
							</button>
							<div class="dropdown-menu scrollable-dropdown-menu" aria-labelledby="dropdownMenuButton-{{ product.id }}">
								{% if product.is_assigned %}
								<a class="dropdown-item" href="{% url 'expert:product-assign' product_pk=product.pk worker_pk=0 %}">---</a>
								{% endif %}
								{% for worker in worker_list %}
								<a class="dropdown-item js-btn-product-assign" href="{% url 'expert:product-assign' product_pk=product.id worker_pk=worker.id %}">{{ worker.username }}</a>
								{% endfor %}
							</div>
						</div>
					</td>
					<td>{{ product.completedby.username }}</td>
					<td>{{ product.date_completed }}</td>
					<td class="
					js-td-status
					status
					{% if product.is_assigned %}bg-warning
					{% elif product.is_dispatched %}bg-dark text-light
					{% elif product.is_completed %}bg-success text-light
					{% elif product.is_returned %}bg-danger{% endif %}
					">{{ product.get_status_display }}</td>
					<td class="text-right">
						{% if product.is_assigned %}
						<a href="{% url 'expert:product-complete' product.id %}" class="btn btn-outline-success btn-sm js-btn-product-complete"><i class="fa fa-check fa-lg"></i></a>
						{% elif product.is_completed and not product.is_dispatched %}
						<a href="{% url 'expert:product-uncomplete' product.id %}" class="btn btn-outline-warning btn-sm js-btn-product-uncomplete" title="UnComplete the Product"><i class="fa fa-ban fa-lg"></i></a>
						{% else %}
						<a href="{% url 'expert:product-complete' product.id %}" class="btn btn-outline-success btn-sm js-btn-product-complete disabled"><i class="fa fa-check fa-lg"></i></a>
						{% endif %}
            			<div class="dropdown d-inline">
            			    <button class="btn btn-sm btn-outline-info dropdown-toggle {% if product.quantity <= 1 or not product.is_pending %}disabled{% endif %}" type="button" id="splitdropdownbutton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Split Product"><i class="fa fa-columns"></i></button>
            			    <div class="dropdown-menu dropdown-menu-right scrollable-dropdown-menu" aria-labelledby="splitdropdownbutton">
								<h6 class="dropdown-header">Split this Product into:</h6>
								<div class="dropdown-divider"></div>
								{% for f in product.split_factors %}
								<a class="dropdown-item" href="{% url 'expert:product-split' pk=product.id %}?factor={{ f }}">{{ f }} parts</a>
								{% endfor %}
            			    </div>
            			</div>
            			<div class="dropdown d-inline">
            			    <button class="btn btn-sm btn-outline-danger dropdown-toggle" type="button" id="returndropdownbutton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="Return Product"><i class="fa fa-recycle"></i></button>
            			    <div class="dropdown-menu" aria-labelledby="returndropdownbutton">
								{% if product.is_dispatched %}
								<a class="dropdown-item {% if product.is_returned %}disabled{% endif %}" href="{% url 'expert:product-return' pk=product.id %}?rr=fault">Fault</a>
								{% else %}
            			        <a class="dropdown-item" href="{% url 'expert:product-return' pk=product.id %}?rr=unprocessed">UnProcessed</a>
            			        <a class="dropdown-item" href="{% url 'expert:product-return' pk=product.id %}?rr=semiprocessed">Semi-Processed</a>
								<a class="dropdown-item" href="{% url 'expert:product-return' pk=product.id %}?rr=mistake">Cutting Mistake</a>
								<a class="dropdown-item" href="{% url 'expert:product-return' pk=product.id %}?rr=damaged">Damaged Goods</a>
								{% endif %}
            			    </div>
            			</div>
						<a href="{% url 'expert:product-delete' product.id %}" class="btn btn-outline-danger btn-sm"><i class="fa fa-trash fa-lg"></i></a>
					</td>

				</tr>
				{% empty %}
				<tr>
					<td colspan="10" class="text-center h5">No Data to display, Please select appropriate filters</td>
				</tr>
				{% endfor %}
			</tbody>
			<tfoot>
				<tr>
					<th></th>
					<th class="border border-success">{{ total_product_quantity }}</th>
					<th class="border border-success">{{ total_product_size|intcomma }} SqFt.</th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</tfoot>
		</table>
		{% block pagination %}
		{% if is_paginated %}
		<nav aria-label="Pagination Nav">
			<ul class="pagination justify-content-end">
				{% if page_obj.has_previous %}
				<li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">&laquo;</a></li>
				{% else %}
				<li class="page-item disabled"><a href="" class="page-link">&laquo;</a></li>
				{% endif %}
				{% for i in paginator.page_range %}
				{% if page_obj.number == i %}
				<li class="page-item active"><a href="" class="page-link">{{ i }}</a></li>
				{% else %}
				<li class="page-item"><a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a></li>
				{% endif %}
				{% endfor %}
				{% if page_obj.has_next %}
				<li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">&raquo;</a></li>
				{% else %}
				<li class="page-item disabled"><a href="" class="page-link">&raquo;</a></li>
				{% endif %}
			</ul>
		</nav>
		{% endif %}
		{% endblock %}
		<div class="my-4">&nbsp;</div>
	</div>
</div>